namespace PanoramicData.Chunker.Models;

/// <summary>
/// Represents visual elements like images, charts, and graphs.
/// </summary>
public class VisualChunk : ChunkerBase
{
	/// <summary>
	/// The caption or alt-text associated with the visual element (if present in the document).
	/// </summary>
	public string? Caption { get; set; }

	/// <summary>
	/// A description of the visual content, potentially generated by an LLM or OCR/VLM.
	/// This is the primary text for vector embedding.
	/// </summary>
	public string? GeneratedDescription { get; set; }

	/// <summary>
	/// The MIME type of the extracted binary data (e.g., "image/png", "image/jpeg").
	/// </summary>
	public string MimeType { get; set; } = string.Empty;

	/// <summary>
	/// Unique hash or URL/identifier for the binary image data.
	/// Used to look up the asset in external storage (e.g., Azure Blob Storage).
	/// </summary>
	public string BinaryReference { get; set; } = string.Empty;

	/// <summary>
	/// Width of the image in pixels (if available).
	/// </summary>
	public int? Width { get; set; }

	/// <summary>
	/// Height of the image in pixels (if available).
	/// </summary>
	public int? Height { get; set; }

	/// <summary>
	/// Size of the binary data in bytes.
	/// </summary>
	public long? SizeInBytes { get; set; }
}
